"""Description of changes

Revision ID: 4f7b735d3f89
Revises: b400e9a61035
Create Date: 2025-09-23 14:52:41.608980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7b735d3f89'
down_revision: Union[str, Sequence[str], None] = 'b400e9a61035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('platform_id', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'users', ['platform_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'platform_id')
    # ### end Alembic commands ###
