"""Description of changes

Revision ID: 72aeb0bb61e0
Revises: 4f7b735d3f89
Create Date: 2025-09-23 14:53:39.061785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72aeb0bb61e0'
down_revision: Union[str, Sequence[str], None] = '4f7b735d3f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'platform_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'platform_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
