"""Description of changes

Revision ID: b400e9a61035
Revises: d98eb8f95ad6
Create Date: 2025-08-30 12:10:56.763579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b400e9a61035'
down_revision: Union[str, Sequence[str], None] = 'd98eb8f95ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('nickname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'nickname')
    # ### end Alembic commands ###
